# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial_common/EnemyPos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EnemyPos(genpy.Message):
  _md5sum = "d278822d8acfbc3aa6895b78b02afb89"
  _type = "serial_common/EnemyPos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 enemy_dist
int32 enemy_yaw
int32 enemy_pitch
int32 mode 
"""
  __slots__ = ['enemy_dist','enemy_yaw','enemy_pitch','mode']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       enemy_dist,enemy_yaw,enemy_pitch,mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EnemyPos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.enemy_dist is None:
        self.enemy_dist = 0
      if self.enemy_yaw is None:
        self.enemy_yaw = 0
      if self.enemy_pitch is None:
        self.enemy_pitch = 0
      if self.mode is None:
        self.mode = 0
    else:
      self.enemy_dist = 0
      self.enemy_yaw = 0
      self.enemy_pitch = 0
      self.mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.enemy_dist, _x.enemy_yaw, _x.enemy_pitch, _x.mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.enemy_dist, _x.enemy_yaw, _x.enemy_pitch, _x.mode,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.enemy_dist, _x.enemy_yaw, _x.enemy_pitch, _x.mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.enemy_dist, _x.enemy_yaw, _x.enemy_pitch, _x.mode,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
